#Zadanie 4 (7 pkt)
Celem zadania jest zaimplementowanie algorytmu drzewa decyzyjnego ID3 dla zadania klasyfikacji. Trening i test należy przeprowadzić dla zbioru Iris. Proszę przeprowadzić eksperymenty najpierw dla DOKŁADNIE takiego podziału zbioru testowego i treningowego jak umieszczony poniżej. W dalszej części należy przeprowadzić analizę działania drzewa dla różnych wartości parametrów. Proszę korzystać z przygotowanego szkieletu programu, oczywiście można go modyfikować według potrzeb. Wszelkie elementy szkieletu zostaną wyjaśnione na zajęciach.

* Implementacja funkcji entropii - **0.5 pkt**
* Implementacja funkcji entropii zbioru - **0.5 pkt**
* Implementacja funkcji information gain - **0.5 pkt**
* Zbudowanie poprawnie działającego drzewa klasyfikacyjnego i przetestowanie go na wspomnianym wcześniej zbiorze testowym. Jeśli w liściu występuje kilka różnych klas, decyzją jest klasa większościowa. Policzenie accuracy i wypisanie parami klasy rzeczywistej i predykcji. - **4 pkt**
* Przeprowadzenie eksperymentów dla różnych głębokości drzew i podziałów zbioru treningowego i testowego (zmiana wartości argumentu test_size oraz usunięcie random_state). W tym przypadku dla każdego eksperymentu należy wykonać kilka uruchomień programu i wypisać dla każdego uruchomienia accuracy. - **1.5 pkt**

In [3]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
import math
from collections import Counter
import numpy as np

iris = load_iris()

x = iris.data
y = iris.target

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.1, random_state=123)

In [14]:
# print(iris.data)
# print(iris.target)
print(x_test)

[[6.3 2.5 4.9 1.5]
 [6.8 3.  5.5 2.1]
 [6.4 2.8 5.6 2.2]
 [5.6 3.  4.1 1.3]
 [4.9 3.6 1.4 0.1]
 [6.  3.  4.8 1.8]
 [6.3 2.3 4.4 1.3]
 [4.4 3.2 1.3 0.2]
 [4.4 2.9 1.4 0.2]
 [5.5 2.6 4.4 1.2]
 [6.9 3.1 5.1 2.3]
 [5.5 4.2 1.4 0.2]
 [5.2 2.7 3.9 1.4]
 [6.5 3.  5.5 1.8]
 [7.7 3.  6.1 2.3]]


In [4]:
def entropy_func(class_count, num_samples):

    # num_samples = number of samples -> ilość wszystkich próbek 
    # class count -> ilość klass? ---- np klasa 0, 1, 2
    # tyle razy będzie trzeba powtórzy pętle zliczając ile jest w tabeli wystąpień dla 0, potem dla 1, 2 --> nie wiem czy to tu czy krok wcześniej 
    # jak zliczymy ilość wystąpień to obliczamy prawdopodobieństwo na podstawie tego wyliczonego / num_samples (ilości wszystkich wierszy w grupie/ wielkości grupy)
    # stosujemy wzór z logarytmem (pamiętaj o - bo nie uwzględniłąm go w klasie group)
    # i dodajemy do sumy 
    probability = class_count/num_samples
    return -probability * math.log2(probability) if probability > 0 else 0


class Group:
    def __init__(self, group_classes):
        self.group_classes = group_classes
        self.entropy = self.group_entropy()

    def __len__(self):
        return self.group_classes.size

    # liczy entropie grupy 
    def group_entropy(self):
        entropy = 0
        counter = Counter(self.group_classes)
        for value, count in counter.items():
            class_count = self.group_classes.count(count)
            entropy += entropy_func(class_count, self.__len__()) # nie jestem pewna czy to len tak może być zapisane ale zobaczymy 
        return entropy
        # policzyć ilośc wystąpienia danej klasy = class_count (np. klasy 0, albo 1 itd.) w group klasses, informacje o klasach dla tej grupy w groyp classes


class Node:
    def __init__(self, split_feature, split_val, depth=None, child_node_a=None, child_node_b=None, val=None):
        self.split_feature = split_feature
        self.split_val = split_val
        self.depth = depth
        self.child_node_a = child_node_a
        self.child_node_b = child_node_b
        self.val = val # może wartość wyliczona przez entropię?

    def predict(self, data):
        pass


class DecisionTreeClassifier(object):
    def __init__(self, max_depth):
        self.depth = 0
        self.max_depth = max_depth
        self.tree = None

    @staticmethod
    def get_split_entropy(group_a, group_b):
        pass

    def get_information_gain(self, parent_group, child_group_a, child_group_b):
        # ta funkcja musi się wykonywać dla kolejych kolumn - atrybutów, w jednej z funckji poniżej 
        parent_entropy = parent_group.group_entropy()
        child_a_entropy = child_group_a.group_entropy()
        child_b_entropy =  child_group_b.group_entropy()
        child_a_parameter = child_group_a.__len__() / parent_group.__len__()
        child_b_parameter = child_group_b.__len__() / parent_group.__len__()
        # return ent(p) - (ilość wiersszy ch_a/ilość wierszy parent * ent(child_1) + (to samo dla b) )
        return parent_entropy - child_a_parameter * child_a_entropy - child_b_parameter * child_b_entropy
        

    def get_best_feature_split(self, feature_values, classes):
        # czy feature values to poprostu numer kolumny???

        # tu może tworzyć obiekty klasy gruop 
        pass

    def get_best_split(self, data, classes):
        pass

    def build_tree(self, data, classes, depth=0):
        # jak tutaj zmieniać dane w date i klases orzy rekurencji ?
        pass

    def predict(self, data):
        return self.tree.predict(data)
    def print_tree(self):
        def print_node(node: Node, indent=""):
            if node.child_node_a is None and node.child_node_b is None:
                print(indent + f"Answer is {node.val}")
            else:
                print(indent + f"Split, feature {node.split_feature}, value -> {node.split_val}")

                print(indent + " -> " + f"(A)")
                print_node(node.child_node_a, indent + "      ")
                
                print(indent + " -> " + f"(B)")
                print_node(node.child_node_b, indent + "      ")
        
        print_node(self.tree)

In [5]:
dc = DecisionTreeClassifier(3)
dc.build_tree(x_train, y_train)
for sample, gt in zip(x_test, y_test):
    prediction = dc.predict(sample)

AttributeError: 'NoneType' object has no attribute 'predict'